apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: peerprep-question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - name: question-service
        image: cpauzi/question-service:latest
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: question-service-configmap
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"